### ISSUE TITLE
Problem with Navilock device

### ISSUE THREAD

**Issue by kolaci** [kconger/android-serial-gps-driver#3]
Hi, I am building navsat device with Navilock GPS receiver (ublox 5 chipset). This device (and probably many others) sends both type of sentences GGA and GSA in every cycle. And this is problem, because your driver sends up valid data with "fix" from the first one and zeroed invalid data with "fix" from the second one. Navigation software is confused, especially speed and altitude values are zero or incorrect.

Fixed code which works well is attached. You can "commit" it to this branch.

BTW, I split original gps.c file to two files - gps.c and nmea.c because of simpler testing of NMEA parser .

Regards,
Martin Kolaci

[gps-driver.zip](https://github.com/kconger/android-serial-gps-driver/files/2545296/gps-driver.zip)

**Comment by Martin-Kolaci** [comment]
Or, you can grant me right to create branch with fix and I will commit fix to GitHub.

**Comment by kconger** [comment]
Hi Martin,

Thanks for the contribution,  I'll take a look soon.

Thanks,
Keith

**Comment by kolaci** [comment]
Hi Keith, please give me access (if you can) to this repository. I would like commit couple of fixes and enhancements to separate branch. Here is some folks which need it: https://forum.emteria.com/discussion/53/gps-module#latest

**Comment by Martin-Kolaci** [comment]
Hi Keith, please give me access (if you can) to this repository. I would like to commit couple of fixes and enhancements to separate branch. Here is some folks which need it: https://forum.emteria.com/discussion/53/gps-module#latest

**Comment by kconger** [comment]
Hi Martin,

Sorry for the delay adding you as a collaborator now.

**Comment by Martin-Kolaci** [comment]
Thank you very much Keith. I pushed new branch gsa-timezone-fix+timesync to
the repo and created pull request. Please could you take a look and review
(if it's necessary) my changes? I tested it on the Emteria Android build
(Raspberry 3b+) and it works well.

Regards,
Martin Kolaci

**Comment by kconger** [comment]
Hi Martin,

Thanks for the enhancements.  I've merged your changes.
