### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by sobrinho** [kconger/android-serial-gps-driver#5]
Hi there!

I can see there are instructions on README but I'm a complete noob with Android building tools (I'm a ruby developer).

I do have the Android source code and I can compile it using a tutorial that I got from Tinker Board UK but how to compile that driver and use it?

**Comment by Martin-Kolaci** [comment]
I don't know if it is simplest way, but I built this driver on Windows as follows:

1) Download NDK from https://developer.android.com/ndk/downloads/
2) Set environmental variable NDK_ROOT to your downloaded NDK, e.g. C:\Sources\android-ndk-r18b
3) Download and unzip attached project
4) Run build.bat located in project directory

After it, built driver should be located in \libs\armeabi-v7a directory.

[android-serial-gps-driver-master.zip](https://github.com/kconger/android-serial-gps-driver/files/2610096/android-serial-gps-driver-master.zip)

**Comment by sobrinho** [comment]
Thanks!

**Comment by sobrinho** [comment]
@Martin-Kolaci can you clarify what is this zip you attached compared to what is on github?

**Comment by Martin-Kolaci** [comment]
Yes, gps.c file is the same as in this master. If you wish, you can download and use it.

**Comment by sobrinho** [comment]
There are a lot more files in your zip.

Do they matter to compile?

**Comment by Martin-Kolaci** [comment]
Yes

**Comment by pepelillo** [comment]
Hi all.
How can compile in linux for x86? can anybody help? or even better if anybody has this library compiled for x86 it would be great, as default serial library in android-x86 project does not work for my ublox-7 usb device.

**Comment by Martin-Kolaci** [comment]
Look at file Application.mk in zip above and set variable APP_ABI to x86 (see https://developer.android.com/ndk/guides/application_mk).

**Comment by sobrinho** [comment]
Closing since I'm no longer using Tinker Board. Thanks! <3
